### ISSUE TITLE
Expose some configuration via MQTT 

### ISSUE THREAD

**Issue by lyuzashi** [lyuzashi/mqtt-smarthome-system#4]
Compose configuration into MQTT topics.

Requires handling of arrays and tool to rebuild config object in memory. 

Discover tree structure by subscribing to a `*` topic and getting all messages under it?

e.g.

```yaml
interfaces:
  lattice:
    modes:
      lighting:
        zones:
         - name: lounge
```

`interfaces/lattice/modes/lighting/zones/0/name` : `lounge`
